

version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        docker_id: ${DOCKER_UID}
        docker_user: ${DOCKER_USER}
    user: ${DOCKER_USER}
    ports:
      - "2345:2345"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ${GOPATH}/pkg:/go/pkg